name: deploy-backend
on:
  push:
    branches:
      - "main"
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          cd backend/api/
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd backend/tests/
          pip install pytest
          python test_api.py
      - name: Build package
        run: |
          cd backend/api
          pip install --target=./package -r requirements.txt
          zip -r ../function.zip .
          cd ../
          mv function.zip ../function.zip
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Azure resources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: resume-challenge
          template: ./azure-resource-template.json
      - name: Deploy Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: azurefunctioncount
          package: ./function.zip
      - name: Logout
        run: |
          az logout
        if: always()
