name: deploy-backend
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          cd backend/api/
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd backend/tests/
          pip install pytest
          python test_api.py
      - name: Set directory permissions
        run: chmod -R 755 backend/api/
      - name: Build package
        run: |
          cd backend/api/
          pip install --target=./package -r requirements.txt
          zip -r ../function.zip .
          ls -a 
          ls -a ..
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: function-zip
          path: backend/function.zip

  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: terraform init
        working-directory: ./backend/
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./backend/
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./backend/

  deploy-function:
    name: 'Deploy Function'
    needs: [terraform, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}","clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId": "${{ secrets.AZURE_TENANT_ID }}"}'
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: function-zip
      - name: List files in backend directory
        run: ls -a ./backend
      - name: Deploy Function App
        run: |
          ls -a 
          az functionapp deployment source config-zip --resource-group azresume-challenge-grp --name azresume-linux-function-app --src function.zip --build-remote true
